HishamWattar/cooks-kingdom

package-lock.json, package.json, yarn.lock
=> Initial folders structure

yarn.lock
I've fixed this error by recreating yarn.lock #17
=> Fix yarn.lock error

src/__tests__/index.js
Fixed this error by adding a test to src/__test__/index.js
=> Fix: GitHub error

src/models/user.js
In this issue, I did the following: #4 
- Add base user schema
- Used discriminator
- Add customer model using a discriminator
- Add chef model using a discriminator
- Add admin model using a discriminator
=> Feature: add user schema

src/models/user.js
In this issue, I did the following:
- Add address schema to user model
- Add array or subdocuments to user schema call `addresses`
Closes #5
=> Feature: add address schema to user model

src/models/review.js
=> Feature: add review schema

src/models/dish.js
#7 its a new one for the dish model.
=> dish.js's schema

.env, .eslintrc.json, package.json, src/__tests__/auth.test.js, src/__tests__/index.js, src/app.js, src/config/passport.js, src/controllers/auth.js, src/routes/auth.js, src/routes/index.js, yarn.lock
- Add Google strategy to src/config/passport.js
- Add both passport middleware and Google strategy to app.js
- Add auth route and controller 
- Add test for Google authentication
Closes #29
=> Feature: add auth with google

.env, package-lock.json, package.json, src/__tests__/auth.test.js, src/config/passport.js, src/db/connection.js, src/routes/auth.js, yarn.lock
Add FB strategy
Add FB endpoints
Add FB tests
Closes #30
=> feature: facebook auth

package.json, src/app.js, src/config/swagger.js, src/docs/user.yaml, yarn.lock
=> setup swagger ui

src/middlewares/auth.js
#40 
- add isAuthenticated middleware to check if the user authenticated
- add isChef, isAdmin, isCustomer middlewares to check if the user authorized
note: I will add the tests when we have endpoints
=> Feature: add middleware

src/app.js, src/middlewares/error.js, src/utils/customError.js
- Add custom Error class extends the builtin class in js
- Add error handling middleware
- Use error handling middleware as global middleware in app.js
Closes #50
=> Feature: add global error handling

package.json, src/__tests__/auth.test.js, src/app.js, src/controllers/auth.js, src/db/connection.js, src/docs/Auth/facebookAuth.yaml, src/docs/Auth/googleAuth.yaml, src/docs/Auth/localAuth.yaml, src/middlewares/validation.js, src/models/user.js, src/routes/auth.js, src/utils/token.js, yarn.lock
- Add signin/signup/signout endpoints
- Add tests for the added endpoints
- Add swagger documentation for all auth endpoints
- Add validation middleware to validate the input 
- Add token utils to reuse in the code 
Closes #31
=> Feature: add local auth

package.json, src/app.js, src/db/connection.js, src/middlewares/error.js, src/middlewares/validation.js, src/utils/logger.js, yarn.lock
- Add winston for logging 
- Add logger to utils/logger.js
- implement logger inside the code
Closes #58
=> Feature: Add logging

src/__tests__/auth.test.js, src/controllers/auth.js, src/docs/Auth/localAuth.yaml, src/middlewares/validation.js, src/routes/auth.js
=> Feature: update password

src/__tests__/admin.test.js, src/__tests__/user.test.js, src/controllers/admin.js, src/controllers/user.js, src/docs/Admin/admin.yaml, src/routes/admin.js, src/utils/email.js
- Add admin approve endpoint
- Update email utils and add new function
- Add test for admin approve
- Add swagger documentation for admin approve
Closes #73
=> Feature: admin approve

src/controllers/dish.js
Update dish controller to get user from req.user instead of req.body.
=> Update to get chef from req

src/__tests__/user.test.js, src/controllers/user.js
- Fix delete address endpoint
- Fix the delete address test in the user test suite
#83
=> Bugs: delete address

src/__tests__/dish.test.js, src/controllers/dish.js, src/middlewares/auth.js, src/models/dish.js, src/routes/dish.js
Update status codes
Hide __v from query results
Add image upload route
Update tests
Delegate 'Item not found" to isOwner middleware
#83
=> Dish Debugging

.env, src/__tests__/admin.test.js, src/__tests__/auth.test.js, src/__tests__/cart.test.js, src/__tests__/dish.test.js, src/__tests__/review.test.js, src/__tests__/user.test.js, src/config/passport.js, src/controllers/user.js, src/docs/Admin/admin.yaml, src/docs/Auth/localAuth.yaml, src/middlewares/validation.js, src/models/user.js
- Update 3rd party authentication and handle the thrown exception
- Update user schema and change name to username
- Update validation
- Update tests
#83
=> Bugs: 3rd party authentication

src/__tests__/cart.test.js, src/controllers/cart.js, src/docs/Cart/cart.yaml, src/routes/cart.js
- Update cart endpoints
- Update cart tests
- Update cart swagger documentation
#83
=> Bugs: cart endpoints

src/__tests__/cart.test.js, src/__tests__/order.test.js, src/controllers/order.js, src/controllers/review.js, src/docs/Order/order.yaml, src/models/cart.js, src/routes/index.js, src/routes/order.js, yarn.lock
- I add routes 
- add routes controller
=> add order routes

src/__tests__/review.test.js, src/controllers/review.js, src/docs/Review/review.yaml, src/middlewares/validation.js, src/routes/review.js
- Fix reviews endpoints
- Fix reviews tests
- Fix reviews swagger
#83
=> Bugs: review

src/__tests__/order.test.js, src/controllers/order.js, src/docs/Order/order.yaml, src/middlewares/validation.js, src/models/order.js, src/routes/order.js
- Fix order endpoints
- Update order model
- Fix order swagger documentation
#83
=> Bugs: order endpoints
